/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-namespace */
import {
  ICountryLists,
  IDropValue,
  IListName,
  ILoaderStatus,
  IRoleNames,
  ITenantDetail,
} from "../types/Types";

export namespace constants {
  export const TenantDetail: ITenantDetail = {
    webURL: `${window.location.origin}${window.location.pathname
      .split("/", 3)
      .join("/")}`,
    tenantURL: `${window.location.origin}`,
  };
  export const fileFlowPath: string = `${window.location.pathname
    .split("/", 3)
    .join("/")}/`;

  export const ListName: IListName = {
    UM_UserDetails: "UM_UserDetails",
    All_Operators: "All_Operators",
    AvailableLicenses: "AvailableLicenses",
    VM_Details: "VM_Details",
    VM_Members: "VM_Members",
    UM_Certifications: "UM_Certifications",
    UM_AllUsers: "UM_AllUsers",
    Set_Unit_Of_Measures: "Set_Unit_Of_Measures",
    Set_Material: "Set_Material",
    Set_Downtime_Reason: "Set_Downtime_Reason",
    Set_Equipment_Type: "Set_Equipment_Type",
    Set_Production_Unit: "Set_Production_Unit",
    AllEquipments: "AllEquipments",
    All_Vendors: "All_Vendors",
    Set_Equipment_Type_Library: "Set_Equipment_Type_Library",
    All_Customers: "All_Customers",
    Common_Datas: "Common_Datas",
    Set_Market_Segment: "Set_Market_Segment",
    Set_Project_Status: "Set_Project_Status",
    Set_Sales_Category: "Set_Sales_Category",
    Set_Pricing_Level: "Set_Pricing_Level",
    Set_Lost_Reason: "Set_Lost_Reason",
    Set_Competitors: "Set_Competitors",
    Set_Engineering_Status: "Set_Engineering_Status",
    Set_Customer_Type: "Set_Customer_Type",
    Set_Vendor_Type: "Set_Vendor_Type",
    Set_Certification_Type: "Set_Certification_Type",
    Set_Departments: "Set_Departments",
    Contacts: "Contacts",
    Customers_Library: "Customers_Library",
    Set_Industry: "Set_Industry",
    Vendors_Library: "Vendors_Library",
    All_Equipments_Library: "All_Equipments_Library",
    Eq_Maintenance_History: "Eq_Maintenance_History",
    Inventory: "Inventory",
    Set_Offices: "Set_Offices",
    Set_Occupation: "Set_Occupation",
    Set_Category: "Set_Category",
    Set_MaintenanceType: "Set_MaintenanceType",
    Set_Region: "Set_Region",
    Error_Logs: "Error_Logs",

    // projects
    PM_LeadsAndOpportunities: "PM_LeadsAndOpportunities",
    PM_Opportunities: "PM_Opportunities",
    PM_Projects: "PM_Projects",
    PM_UniqueIDsForTheAnnualTeam: "PM_UniqueIDsForTheAnnualTeam",
    PM_Literature: "PM_Literature",
    PM_Techniques: "PM_Techniques",
    PM_PreDrillingData: "PM_PreDrillingData",
    PM_ProductionData: "PM_ProductionData",
    PM_Production_Shift: "PM_Production_Shift",
    PM_Timesheet: "PM_Timesheet",
    PM_Equipment: "PM_Equipment",
    PM_Downtime: "PM_Downtime",
    PM_Notes: "PM_Notes",
    PM_Gallery: "PM_Gallery",
    PM_Weather: "PM_Weather",
    PM_MaterialDelivered: "PM_MaterialDelivered",

    // Organization details
    Org_details: "Org_details",
  };

  //   export const SafetyLists: ISafetyLists = {
  //     SF_DailyHuddle: "SF_DailyHuddle",
  //     SF_CraneOperator: "SF_CraneOperator",
  //     SF_CraneInspection: "SF_CraneInspection",
  //     SF_ProjectSafetyPlan: "SF_Project_Safety_Plan",
  //     SF_DrillOperatorEvaluation: "SF_DrillOperatorEvaluation",
  //     SF_MEWPOperatorEvaluation: "SF_MEWPOperatorEvaluation",
  //     SF_ForkLiftOperatorEvaluation: "SF_ForkLiftOperatorEvaluation",
  //     SF_Safety_Observation: "SF_Reports_Safety_Observation",
  //     SF_AutoPropertyIncident: "SF_AutoPropertyIncident",
  //     SF_UtilityDamageReport: "SF_UtilityDamageReport",
  //     SF_Drill_Rig_Inspection: "SF_Drill_Rig_Inspection",
  //     SF_Mobile_Equipment_Inspection: "SF_Mobile_Equipment_Inspection",
  //     SF_Stationary_Equipment_Inspection: "SF_Stationary_Equipment_Inspection",
  //     SF_Reports_Near_Miss: "SF_Reports_Near_Miss",
  //     SF_Reports_Injury: "SF_Reports_Injury",
  //     SF_Reports_Witness_Statement: "SF_Reports_Witness_Statement",
  //   };

  //   export const PM_OpportunitiesColumn: IPM_OpportunitiesColumn = {
  //     ID: "ID",
  //     Title: "Title",
  //     OpportunitieCount: "OpportunitieCount",
  //     Name: "Name",
  //     ProjectManager: "ProjectManagerId",
  //     ProjectExecutive: "ProjectExecutiveId",
  //     ProjectTeam: "ProjectTeamId",
  //     Region: "Region",
  //     Customer: "CustomerId",
  //     Status: "Status",
  //     // City: "City",
  //     LeadDate: "LeadDate",
  //     Address: "Address",
  //     Description: "Description",
  //     IsProject: "IsProject",
  //     ChannelSiteName: "ChannelSiteName",
  //     ChannelName: "ChannelName",
  //     siteURL: "siteURL",
  //   };

  //   export const PM_OpportunitiesObject: IPM_OpportunitiesObject = {
  //     Title: "",
  //     Address: "",
  //     // City: "",
  //     Description: "",
  //     ID: null,
  //     IsProject: false,
  //     LeadDate: "",
  //     ProjectExecutive: null,
  //     ProjectManager: null,
  //     ProjectTeam: null,
  //     Name: "",
  //     Region: "",
  //     Customer: "",
  //     Status: "Pricing Due",
  //     CreatedBy: null,
  //     files: [],
  //     ChannelSiteName: "",
  //     ChannelName: "",
  //     siteURL: "",
  //   };

  //   export const PM_ProjectsColumn: IPM_ProjectsColumn = {
  //     ID: "ID",
  //     Title: "Title",
  //     ProjectCount: "ProjectCount",
  //     Name: "Name",
  //     ProjectManager: "ProjectManagerId",
  //     ProjectExecutive: "ProjectExecutiveId",
  //     ProjectTeam: "ProjectTeamId",
  //     Customer: "CustomerId",
  //     Status: "Status",
  //     City: "City",
  //     State: "State",
  //     Address: "Address",
  //     LeadDate: "LeadDate",
  //     Description: "Description",
  //     ChannelSiteName: "ChannelSiteName",
  //     ChannelName: "ChannelName",
  //     siteURL: "siteURL",
  //     ProjectFromId: "ProjectFromId",
  //     Duration: "Duration",
  //     ManHours: "ManHours",
  //     BidDueDate: "BidDueDate",
  //     BidAmount: "BidAmount",
  //     PricingLevel: "PricingLevel",
  //     Region: "Region",
  //     OpportunityNo: "OpportunityNo",
  //   };

  //   export const PM_ProjectsObject: IPM_ProjectsObject = {
  //     Title: "",
  //     Address: "",
  //     City: "",
  //     State: "",
  //     Description: "",
  //     ID: null,
  //     LeadDate: "",
  //     ProjectExecutive: null,
  //     ProjectManager: null,
  //     ProjectTeam: null,
  //     Name: "",
  //     Status: "",
  //     CreatedBy: null,
  //     files: [],
  //     ChannelSiteName: "",
  //     ChannelName: "",
  //     siteURL: "",
  //     Customer: "",
  //     Duration: "",
  //     ManHours: "",
  //     BidDueDate: "",
  //     BidAmount: "",
  //     PricingLevel: "",
  //     Region: "",
  //   };

  //   export const PM_LeadsAndOpportunitiesColumn: IPM_LeadsAndOpportunitiesColumn =
  //     {
  //       ID: "ID",
  //       Title: "Title",
  //       OpportunitieCount: "OpportunitieCount",
  //       ProjectCount: "ProjectCount",
  //       Name: "Name",
  //       ProjectManager: "ProjectManagerId",
  //       ProjectExecutive: "ProjectExecutiveId",
  //       ProjectTeam: "ProjectTeamId",
  //       Region: "Region",
  //       Customer: "CustomerId",
  //       Status: "Status",
  //       // City: "City",
  //       LeadDate: "LeadDate",
  //       Address: "Address",
  //       Description: "Description",
  //       IsProject: "IsProject",
  //       ChannelSiteName: "ChannelSiteName",
  //       ChannelProjectSiteName: "ChannelProjectSiteName",
  //     };

  //   export const PM_LeadsAndOpportunitiesObject: IPM_LeadsAndOpportunitiesObject =
  //     {
  //       Title: "",
  //       Address: "",
  //       City: "",
  //       State: "",
  //       BidDueDate: "",
  //       PricingLevel: "",
  //       Description: "",
  //       ID: null,
  //       IsProject: false,
  //       LeadDate: "",
  //       ProjectExecutive: null,
  //       ProjectManager: null,
  //       ProjectTeam: null,
  //       Name: "",
  //       Region: "",
  //       Customer: "",
  //       Status: "",
  //       CreatedBy: null,
  //       files: [],
  //       ChannelSiteName: "",
  //       ChannelProjectSiteName: "",
  //     };

  //   export const LAOSearchObject: ILAOSearchObject = {
  //     No: "",
  //     Search: "",
  //     Region: "",
  //     Status: "",
  //     MarketSegment: "",
  //     Technique: "",
  //   };

  //   export const TeamName: ITeamName = {
  //     OppTeamName: "Opportunities",
  //     ProTeamName: "Projects",
  //   };

  //   export const TeamIds: ITeamIds = {
  //     OppTeamId: "",
  //     ProTeamId: "",
  //   };

  //   export const StatCardDetail: IStatCardDetail = {
  //     ContractsRec: {
  //       count: 0,
  //       isPositive: false,
  //       percentage: "",
  //     },
  //     LostCon: {
  //       count: 0,
  //       isPositive: false,
  //       percentage: "",
  //     },
  //     totalOpp: {
  //       count: 0,
  //       isPositive: false,
  //       percentage: "",
  //     },
  //   };

  //   export const FolderPath: IFolderPath[] = [
  //     {
  //       name: "1-Drawings",
  //       child: [
  //         {
  //           name: "Architectural",
  //           child: [],
  //         },
  //         {
  //           name: "Civil",
  //           child: [],
  //         },
  //         {
  //           name: "Structural",
  //           child: [],
  //         },
  //       ],
  //     },
  //     {
  //       name: "2-Soils Info",
  //       child: [],
  //     },
  //     {
  //       name: "3-Specifications",
  //       child: [],
  //     },
  //     {
  //       name: "4-RFI's & Addendums",
  //       child: [],
  //     },
  //     {
  //       name: "5-Pricing",
  //       child: [],
  //     },
  //     {
  //       name: "6-Contract",
  //       child: [
  //         {
  //           name: "01-Subcontract",
  //           child: [],
  //         },
  //         {
  //           name: "02-Change Orders",
  //           child: [],
  //         },
  //         {
  //           name: "03-Insurance",
  //           child: [],
  //         },
  //         {
  //           name: "04-Pay Apps",
  //           child: [],
  //         },
  //         {
  //           name: "05-NTO & ROL's",
  //           child: [],
  //         },
  //       ],
  //     },
  //     {
  //       name: "7-Safety",
  //       child: [],
  //     },
  //     {
  //       name: "8-Technical",
  //       child: [
  //         {
  //           name: "01-CAD",
  //           child: [],
  //         },
  //         {
  //           name: "02-Loads",
  //           child: [],
  //         },
  //         {
  //           name: "03-Design",
  //           child: [],
  //         },
  //         {
  //           name: "04-Submittals",
  //           child: [],
  //         },
  //         {
  //           name: "05-Certification",
  //           child: [],
  //         },
  //       ],
  //     },
  //     {
  //       name: "9-Field Reports",
  //       child: [
  //         {
  //           name: "01-Production",
  //           child: [],
  //         },
  //         {
  //           name: "02-Daily Report",
  //           child: [],
  //         },
  //         {
  //           name: "03-Time Sheet",
  //           child: [],
  //         },
  //         {
  //           name: "04-Material Delivered",
  //           child: [],
  //         },
  //         {
  //           name: "05-Photos",
  //           child: [],
  //         },
  //       ],
  //     },
  //     {
  //       name: "10-Invoices",
  //       child: [],
  //     },
  //   ];

  export const masterRoles: IRoleNames = {
    AdminAssistant: "Admin Assistant",
    AreaManager: "Area Manager",
    AssistantProjectManager: "Assistant Project Manager",
    Bookkeeper: "Bookkeeper",
    CadSpecialist: "Cad Specialist",
    ChiefEngineer: "Chief Engineer",
    Controller: "Controller",
    DepartmentManager: "Department Manager",
    DesignEngineer: "Design Engineer",
    Foreman: "Foreman",
    HRManager: "HR Manager",
    MarketingCoordinator: "Marketing Coordinator",
    OperationsManager: "Operations Manager",
    President: "President",
    ProcurementManager: "Procurement Manager",
    ProjectEngineer: "Project Engineer",
    ProjectManager: "Project Manager",
    SafetyManager: "Safety Manager",
    SeniorDesignEngineer: "Senior Design Engineer",
    SeniorProjectManager: "Senior Project Manager",
    Superintedent: "Superintedent",
  };

  //   export const jobTitles = [
  //     { label: masterRoles.President, value: masterRoles.President },
  //     {
  //       label: masterRoles.DepartmentManager,
  //       value: masterRoles.DepartmentManager,
  //     },
  //     { label: masterRoles.AreaManager, value: masterRoles.AreaManager },
  //     {
  //       label: masterRoles.SeniorProjectManager,
  //       value: masterRoles.SeniorProjectManager,
  //     },
  //     { label: masterRoles.ProjectManager, value: masterRoles.ProjectManager },
  //     {
  //       label: masterRoles.AssistantProjectManager,
  //       value: masterRoles.AssistantProjectManager,
  //     },
  //     { label: masterRoles.ProjectEngineer, value: masterRoles.ProjectEngineer },
  //     { label: masterRoles.Superintedent, value: masterRoles.Superintedent },
  //     { label: masterRoles.Foreman, value: masterRoles.Foreman },
  //     // { label: "Operator", value: "Operator" },
  //     // { label: "Labor", value: "Labor" },
  //     { label: masterRoles.ChiefEngineer, value: masterRoles.ChiefEngineer },
  //     {
  //       label: masterRoles.SeniorDesignEngineer,
  //       value: masterRoles.SeniorDesignEngineer,
  //     },
  //     { label: masterRoles.DesignEngineer, value: masterRoles.DesignEngineer },
  //     { label: masterRoles.CadSpecialist, value: masterRoles.CadSpecialist },
  //     { label: masterRoles.SafetyManager, value: masterRoles.SafetyManager },
  //     { label: masterRoles.Controller, value: masterRoles.Controller },
  //     { label: masterRoles.Bookkeeper, value: masterRoles.Bookkeeper },
  //     { label: masterRoles.HRManager, value: masterRoles.HRManager },
  //     { label: masterRoles.AdminAssistant, value: masterRoles.AdminAssistant },
  //     {
  //       label: masterRoles.OperationsManager,
  //       value: masterRoles.OperationsManager,
  //     },
  //     {
  //       label: masterRoles.ProcurementManager,
  //       value: masterRoles.ProcurementManager,
  //     },
  //     {
  //       label: masterRoles.MarketingCoordinator,
  //       value: masterRoles.MarketingCoordinator,
  //     },
  //   ];

  //   export const departments = [
  //     { label: "Administration", value: "Administration" },
  //     { label: "Accounting", value: "Accounting" },
  //     { label: "Engineering", value: "Engineering" },
  //     { label: "Operations", value: "Operations" },
  //     { label: "Shop", value: "Shop" },
  //     { label: "Marketing", value: "Marketing" },
  //   ];

  //   export const SPGroupSiteMembers: string = "Site Members";

  export const LoaderStatus: ILoaderStatus = {
    requestProcessing: false,
    dataFetching: true,
    message: "",
    promiseResolved: false,
    isLoading: false,
    errorCode: "",
    errorName: "",
  };

  //   export const ProfileTabs: IProfileTabs = {
  //     Overview: "Overview",
  //     Bio: "Bio",
  //     Licenses: "Licenses",
  //     FolderAndDocuments: "Folder & Documents",
  //     CertificationsAndTraining: "Certifications & Training",
  //     Projects: "Projects",
  //   };

  //   export const ProfileTabLists: string[] = [
  //     ProfileTabs.Overview,
  //     ProfileTabs.Bio,
  //     ProfileTabs.Licenses,
  //     ProfileTabs.FolderAndDocuments,
  //     ProfileTabs.CertificationsAndTraining,
  //     ProfileTabs.Projects,
  //   ];

  //   export const ProfileTabListsWithComponents = [
  //     Overview,
  //     Bio,
  //     Licenses,
  //     FilesFolders,
  //     Certifications,
  //     ProjectsView,
  //   ];

  //   export const AzureUserFields = [
  //     "id",
  //     "givenName",
  //     "surname",
  //     "userPrincipalName",
  //     "displayName",
  //     "jobTitle",
  //     "department",
  //     "employeeHireDate",
  //     "streetAddress",
  //     "city",
  //     "state",
  //     "postalCode",
  //     "country",
  //     "accountEnabled",
  //     "createdDateTime",
  //     "mobilePhone",
  //   ];

  //   export const AzureRequiredUserFieldsForUpdate: string[] = [
  //     "FirstName",
  //     "LastName",
  //     "AZDisplayName",
  //     "JobTitle",
  //     "Department",
  //     "DateOfJoining",
  //     "Address",
  //     // "City",
  //     // "State",
  //     // "PostalCode",
  //     // "Country",
  //   ];

  export const CountryLists: ICountryLists[] = [
    { name: "Afghanistan", code: "AF" },
    { name: "Åland Islands", code: "AX" },
    { name: "Albania", code: "AL" },
    { name: "Algeria", code: "DZ" },
    { name: "American Samoa", code: "AS" },
    { name: "AndorrA", code: "AD" },
    { name: "Angola", code: "AO" },
    { name: "Anguilla", code: "AI" },
    { name: "Antarctica", code: "AQ" },
    { name: "Antigua and Barbuda", code: "AG" },
    { name: "Argentina", code: "AR" },
    { name: "Armenia", code: "AM" },
    { name: "Aruba", code: "AW" },
    { name: "Australia", code: "AU" },
    { name: "Austria", code: "AT" },
    { name: "Azerbaijan", code: "AZ" },
    { name: "Bahamas", code: "BS" },
    { name: "Bahrain", code: "BH" },
    { name: "Bangladesh", code: "BD" },
    { name: "Barbados", code: "BB" },
    { name: "Belarus", code: "BY" },
    { name: "Belgium", code: "BE" },
    { name: "Belize", code: "BZ" },
    { name: "Benin", code: "BJ" },
    { name: "Bermuda", code: "BM" },
    { name: "Bhutan", code: "BT" },
    { name: "Bolivia", code: "BO" },
    { name: "Bosnia and Herzegovina", code: "BA" },
    { name: "Botswana", code: "BW" },
    { name: "Bouvet Island", code: "BV" },
    { name: "Brazil", code: "BR" },
    { name: "British Indian Ocean Territory", code: "IO" },
    { name: "Brunei Darussalam", code: "BN" },
    { name: "Bulgaria", code: "BG" },
    { name: "Burkina Faso", code: "BF" },
    { name: "Burundi", code: "BI" },
    { name: "Cambodia", code: "KH" },
    { name: "Cameroon", code: "CM" },
    { name: "Canada", code: "CA" },
    { name: "Cape Verde", code: "CV" },
    { name: "Cayman Islands", code: "KY" },
    { name: "Central African Republic", code: "CF" },
    { name: "Chad", code: "TD" },
    { name: "Chile", code: "CL" },
    { name: "China", code: "CN" },
    { name: "Christmas Island", code: "CX" },
    { name: "Cocos (Keeling) Islands", code: "CC" },
    { name: "Colombia", code: "CO" },
    { name: "Comoros", code: "KM" },
    { name: "Congo", code: "CG" },
    { name: "Congo, The Democratic Republic of the", code: "CD" },
    { name: "Cook Islands", code: "CK" },
    { name: "Costa Rica", code: "CR" },
    { name: "Cote D'Ivoire", code: "CI" },
    { name: "Croatia", code: "HR" },
    { name: "Cuba", code: "CU" },
    { name: "Cyprus", code: "CY" },
    { name: "Czech Republic", code: "CZ" },
    { name: "Denmark", code: "DK" },
    { name: "Djibouti", code: "DJ" },
    { name: "Dominica", code: "DM" },
    { name: "Dominican Republic", code: "DO" },
    { name: "Ecuador", code: "EC" },
    { name: "Egypt", code: "EG" },
    { name: "El Salvador", code: "SV" },
    { name: "Equatorial Guinea", code: "GQ" },
    { name: "Eritrea", code: "ER" },
    { name: "Estonia", code: "EE" },
    { name: "Ethiopia", code: "ET" },
    { name: "Falkland Islands (Malvinas)", code: "FK" },
    { name: "Faroe Islands", code: "FO" },
    { name: "Fiji", code: "FJ" },
    { name: "Finland", code: "FI" },
    { name: "France", code: "FR" },
    { name: "French Guiana", code: "GF" },
    { name: "French Polynesia", code: "PF" },
    { name: "French Southern Territories", code: "TF" },
    { name: "Gabon", code: "GA" },
    { name: "Gambia", code: "GM" },
    { name: "Georgia", code: "GE" },
    { name: "Germany", code: "DE" },
    { name: "Ghana", code: "GH" },
    { name: "Gibraltar", code: "GI" },
    { name: "Greece", code: "GR" },
    { name: "Greenland", code: "GL" },
    { name: "Grenada", code: "GD" },
    { name: "Guadeloupe", code: "GP" },
    { name: "Guam", code: "GU" },
    { name: "Guatemala", code: "GT" },
    { name: "Guernsey", code: "GG" },
    { name: "Guinea", code: "GN" },
    { name: "Guinea-Bissau", code: "GW" },
    { name: "Guyana", code: "GY" },
    { name: "Haiti", code: "HT" },
    { name: "Heard Island and Mcdonald Islands", code: "HM" },
    { name: "Holy See (Vatican City State)", code: "VA" },
    { name: "Honduras", code: "HN" },
    { name: "Hong Kong", code: "HK" },
    { name: "Hungary", code: "HU" },
    { name: "Iceland", code: "IS" },
    { name: "India", code: "IN" },
    { name: "Indonesia", code: "ID" },
    { name: "Iran, Islamic Republic Of", code: "IR" },
    { name: "Iraq", code: "IQ" },
    { name: "Ireland", code: "IE" },
    { name: "Isle of Man", code: "IM" },
    { name: "Israel", code: "IL" },
    { name: "Italy", code: "IT" },
    { name: "Jamaica", code: "JM" },
    { name: "Japan", code: "JP" },
    { name: "Jersey", code: "JE" },
    { name: "Jordan", code: "JO" },
    { name: "Kazakhstan", code: "KZ" },
    { name: "Kenya", code: "KE" },
    { name: "Kiribati", code: "KI" },
    { name: "Korea, Democratic People'S Republic of", code: "KP" },
    { name: "Korea, Republic of", code: "KR" },
    { name: "Kuwait", code: "KW" },
    { name: "Kyrgyzstan", code: "KG" },
    { name: "Lao People'S Democratic Republic", code: "LA" },
    { name: "Latvia", code: "LV" },
    { name: "Lebanon", code: "LB" },
    { name: "Lesotho", code: "LS" },
    { name: "Liberia", code: "LR" },
    { name: "Libyan Arab Jamahiriya", code: "LY" },
    { name: "Liechtenstein", code: "LI" },
    { name: "Lithuania", code: "LT" },
    { name: "Luxembourg", code: "LU" },
    { name: "Macao", code: "MO" },
    { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
    { name: "Madagascar", code: "MG" },
    { name: "Malawi", code: "MW" },
    { name: "Malaysia", code: "MY" },
    { name: "Maldives", code: "MV" },
    { name: "Mali", code: "ML" },
    { name: "Malta", code: "MT" },
    { name: "Marshall Islands", code: "MH" },
    { name: "Martinique", code: "MQ" },
    { name: "Mauritania", code: "MR" },
    { name: "Mauritius", code: "MU" },
    { name: "Mayotte", code: "YT" },
    { name: "Mexico", code: "MX" },
    { name: "Micronesia, Federated States of", code: "FM" },
    { name: "Moldova, Republic of", code: "MD" },
    { name: "Monaco", code: "MC" },
    { name: "Mongolia", code: "MN" },
    { name: "Montserrat", code: "MS" },
    { name: "Morocco", code: "MA" },
    { name: "Mozambique", code: "MZ" },
    { name: "Myanmar", code: "MM" },
    { name: "Namibia", code: "NA" },
    { name: "Nauru", code: "NR" },
    { name: "Nepal", code: "NP" },
    { name: "Netherlands", code: "NL" },
    { name: "Netherlands Antilles", code: "AN" },
    { name: "New Caledonia", code: "NC" },
    { name: "New Zealand", code: "NZ" },
    { name: "Nicaragua", code: "NI" },
    { name: "Niger", code: "NE" },
    { name: "Nigeria", code: "NG" },
    { name: "Niue", code: "NU" },
    { name: "Norfolk Island", code: "NF" },
    { name: "Northern Mariana Islands", code: "MP" },
    { name: "Norway", code: "NO" },
    { name: "Oman", code: "OM" },
    { name: "Pakistan", code: "PK" },
    { name: "Palau", code: "PW" },
    { name: "Palestinian Territory, Occupied", code: "PS" },
    { name: "Panama", code: "PA" },
    { name: "Papua New Guinea", code: "PG" },
    { name: "Paraguay", code: "PY" },
    { name: "Peru", code: "PE" },
    { name: "Philippines", code: "PH" },
    { name: "Pitcairn", code: "PN" },
    { name: "Poland", code: "PL" },
    { name: "Portugal", code: "PT" },
    { name: "Puerto Rico", code: "PR" },
    { name: "Qatar", code: "QA" },
    { name: "Reunion", code: "RE" },
    { name: "Romania", code: "RO" },
    { name: "Russian Federation", code: "RU" },
    { name: "RWANDA", code: "RW" },
    { name: "Saint Helena", code: "SH" },
    { name: "Saint Kitts and Nevis", code: "KN" },
    { name: "Saint Lucia", code: "LC" },
    { name: "Saint Pierre and Miquelon", code: "PM" },
    { name: "Saint Vincent and the Grenadines", code: "VC" },
    { name: "Samoa", code: "WS" },
    { name: "San Marino", code: "SM" },
    { name: "Sao Tome and Principe", code: "ST" },
    { name: "Saudi Arabia", code: "SA" },
    { name: "Senegal", code: "SN" },
    { name: "Serbia and Montenegro", code: "CS" },
    { name: "Seychelles", code: "SC" },
    { name: "Sierra Leone", code: "SL" },
    { name: "Singapore", code: "SG" },
    { name: "Slovakia", code: "SK" },
    { name: "Slovenia", code: "SI" },
    { name: "Solomon Islands", code: "SB" },
    { name: "Somalia", code: "SO" },
    { name: "South Africa", code: "ZA" },
    { name: "South Georgia and the South Sandwich Islands", code: "GS" },
    { name: "Spain", code: "ES" },
    { name: "Sri Lanka", code: "LK" },
    { name: "Sudan", code: "SD" },
    { name: "Suriname", code: "SR" },
    { name: "Svalbard and Jan Mayen", code: "SJ" },
    { name: "Swaziland", code: "SZ" },
    { name: "Sweden", code: "SE" },
    { name: "Switzerland", code: "CH" },
    { name: "Syrian Arab Republic", code: "SY" },
    { name: "Taiwan, Province of China", code: "TW" },
    { name: "Tajikistan", code: "TJ" },
    { name: "Tanzania, United Republic of", code: "TZ" },
    { name: "Thailand", code: "TH" },
    { name: "Timor-Leste", code: "TL" },
    { name: "Togo", code: "TG" },
    { name: "Tokelau", code: "TK" },
    { name: "Tonga", code: "TO" },
    { name: "Trinidad and Tobago", code: "TT" },
    { name: "Tunisia", code: "TN" },
    { name: "Turkey", code: "TR" },
    { name: "Turkmenistan", code: "TM" },
    { name: "Turks and Caicos Islands", code: "TC" },
    { name: "Tuvalu", code: "TV" },
    { name: "Uganda", code: "UG" },
    { name: "Ukraine", code: "UA" },
    { name: "United Arab Emirates", code: "AE" },
    { name: "United Kingdom", code: "GB" },
    { name: "United States", code: "US" },
    { name: "United States Minor Outlying Islands", code: "UM" },
    { name: "Uruguay", code: "UY" },
    { name: "Uzbekistan", code: "UZ" },
    { name: "Vanuatu", code: "VU" },
    { name: "Venezuela", code: "VE" },
    { name: "Viet Nam", code: "VN" },
    { name: "Virgin Islands, British", code: "VG" },
    { name: "Virgin Islands, U.S.", code: "VI" },
    { name: "Wallis and Futuna", code: "WF" },
    { name: "Western Sahara", code: "EH" },
    { name: "Yemen", code: "YE" },
    { name: "Zambia", code: "ZM" },
    { name: "Zimbabwe", code: "ZW" },
  ];

  export const ADGroupNames: IDropValue[] = [
    {
      label: "President",
      value: "AD_President",
    },
    {
      label: "Department Manager",
      value: "AD_DepartmentManager",
    },
    {
      label: "Area Manager",
      value: "AD_AreaManager",
    },
    {
      label: "Senior Project Manager",
      value: "AD_SeniorProjectManager",
    },
    {
      label: "Project Manager",
      value: "AD_ProjectManager",
    },
    {
      label: "Assistant Project Manager",
      value: "AD_AssistantProjectManager",
    },
    {
      label: "Project Engineer",
      value: "AD_ProjectEngineer",
    },
    {
      label: "Superintedent",
      value: "AD_Superintedent",
    },
    {
      label: "Foreman",
      value: "AD_Foreman",
    },
    {
      label: "Operator",
      value: "AD_Operator",
    },
    {
      label: "Labor",
      value: "AD_Labor",
    },
    {
      label: "Chief Engineer",
      value: "AD_ChiefEngineer",
    },
    {
      label: "Senior Design Engineer",
      value: "AD_SeniorDesignEngineer",
    },
    {
      label: "Design Engineer",
      value: "AD_Designengineer",
    },
    {
      label: "Cad Specialist",
      value: "AD_CadSpecialist",
    },
    {
      label: "Safety Manager",
      value: "AD_SafetyManager",
    },
    {
      label: "Controller",
      value: "AD_Controller",
    },
    {
      label: "Bookkeeper",
      value: "AD_Bookkeeper",
    },
    {
      label: "HR Manager",
      value: "AD_HRManager",
    },
    {
      label: "Admin Assistant",
      value: "AD_AdminAssistant",
    },
    {
      label: "Operations Manager",
      value: "AD_OperationsManager",
    },
    {
      label: "Procurement Manager",
      value: "AD_ProcurementManager",
    },
    {
      label: "Marketing Coordinator",
      value: "AD_MarketingCoordinator",
    },
    {
      label: "Geotek Super Admin",
      value: "Geotek_Super_Admin",
    },
  ];
}
